-- 테이블 생성 (COLUMN : 7)
CREATE TABLE ATTENDANCE(
    ATT_NO NUMBER(20) NOT NULL CONSTRAINT PK_ATTENDANCE PRIMARY KEY,
    MEMBER_NUM  NUMBER(20) NOT NULL 
                CONSTRAINT ATTENDANCE_MEMBER_NO_FK REFERENCES MEMBER(MEMBER_NUM),-- 외래키 자유
	ATT_DATE    DATE DEFAULT SYSDATE,
    ATT_START   VARCHAR2(80),
    ATT_FIN     VARCHAR2(80),
    ATT_TOTAL   NUMBER,
    ATT_STATUS  VARCHAR2(80)
) ;

COMMIT;