--------------------------------------------------------
--  파일이 생성됨 - 수요일-8월-30-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MAIL
--------------------------------------------------------

  CREATE TABLE "PROJECT"."MAIL" 
   (	"MAIL_NUM" NUMBER, 
	"MAIL_TITLE" VARCHAR2(100 BYTE), 
	"MAIL_CONTENT" VARCHAR2(500 BYTE) DEFAULT '내용없음', 
	"MAIL_SENDER" VARCHAR2(30 BYTE), 
	"MAIL_FROM_DATE" DATE, 
	"MAIL_TO_DATE" DATE DEFAULT SYSDATE, 
	"MAIL_REFEREE" VARCHAR2(20 BYTE) DEFAULT SYSDATE, 
	"REF_NUM" NUMBER, 
	"MAIL_RECEIVER" VARCHAR2(50 BYTE), 
	"REC_NUM" NUMBER, 
	"REC_STATUS" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"MAIL_FILENUM" NUMBER, 
	"MAIL_FILENAME" VARCHAR2(20 BYTE), 
	"MAIL_FILEPATH" VARCHAR2(500 BYTE), 
	"MEMBER_NUM" NUMBER, 
	"MAIL_FILERENAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."MAIL_PK" ON "PROJECT"."MAIL" ("MAIL_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MAIL
--------------------------------------------------------

  ALTER TABLE "PROJECT"."MAIL" MODIFY ("MAIL_NUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MAIL" MODIFY ("MAIL_TITLE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MAIL" MODIFY ("MAIL_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MAIL" MODIFY ("MAIL_SENDER" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MAIL" MODIFY ("MAIL_FROM_DATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MAIL" MODIFY ("MAIL_TO_DATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MAIL" MODIFY ("REC_NUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MAIL" MODIFY ("MEMBER_NUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MAIL" ADD CONSTRAINT "MAIL_PK" PRIMARY KEY ("MAIL_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAIL
--------------------------------------------------------

  ALTER TABLE "PROJECT"."MAIL" ADD CONSTRAINT "MAIL_MEMBER_MEMBERNUM_FK" FOREIGN KEY ("MEMBER_NUM")
	  REFERENCES "PROJECT"."MEMBER" ("MEMBER_NUM") ENABLE;
