CREATE TABLE COMMUNITY_FILES (
    COM_NUM NUMBER(20) NOT NULL,
    ORIGINAL_FILENAME VARCHAR2(255) NOT NULL,
    STORE_FILENAME VARCHAR2(255) NOT NULL
);

CREATE TABLE COMMUNITY_IMAGES (
    COM_NUM NUMBER(20) NOT NULL,
    ORIGINAL_FILENAME VARCHAR2(255) NOT NULL,
    STORE_FILENAME VARCHAR2(255) NOT NULL
);