REM INSERTING into PROJECT.FILE_BOARD
SET DEFINE OFF;
Insert into PROJECT.FILE_BOARD (FILE_BOARD_NO,MEMBER_NUM,FILE_BOARD_DATE,FILE_BOARD_TITLE,FILE_BOARD_CONTENT,FILE_BOARD_VIEW,FILE_NAME,FILE_RENAME,FILE_PATH) values (1,'2',to_date('23/08/17','RR/MM/DD'),'4','5',6,'7','8','9');
Insert into PROJECT.FILE_BOARD (FILE_BOARD_NO,MEMBER_NUM,FILE_BOARD_DATE,FILE_BOARD_TITLE,FILE_BOARD_CONTENT,FILE_BOARD_VIEW,FILE_NAME,FILE_RENAME,FILE_PATH) values (2,'test2',to_date('23/08/28','RR/MM/DD'),'testtitle2','testcontent2',2,'testname2','testrename2','top');
Insert into PROJECT.FILE_BOARD (FILE_BOARD_NO,MEMBER_NUM,FILE_BOARD_DATE,FILE_BOARD_TITLE,FILE_BOARD_CONTENT,FILE_BOARD_VIEW,FILE_NAME,FILE_RENAME,FILE_PATH) values (3,'test3',to_date('23/08/28','RR/MM/DD'),'testtitle3','testcontent3',3,'testname3','testrename3','top');
