--------------------------------------------------------
--  파일이 생성됨 - 월요일-10월-16-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FILE_BOARD
--------------------------------------------------------

  CREATE TABLE "PROJECT"."FILE_BOARD" 
   (	"FILE_BOARD_NO" NUMBER, 
	"MEMBER_NUM" NUMBER, 
	"FILE_BOARD_DATE" DATE DEFAULT SYSDATE, 
	"FILE_BOARD_TITLE" VARCHAR2(1000 BYTE), 
	"FILE_BOARD_CONTENT" VARCHAR2(3999 BYTE), 
	"FILE_BOARD_VIEW" NUMBER, 
	"FILE_NAME" VARCHAR2(1000 BYTE), 
	"FILE_RENAME" VARCHAR2(1000 BYTE), 
	"FILE_PATH" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."FILE_BOARD_NO" IS '자료게시글번호';
   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."MEMBER_NUM" IS '사원번호';
   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."FILE_BOARD_DATE" IS '자료작성날짜';
   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."FILE_BOARD_TITLE" IS '자료제목';
   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."FILE_BOARD_CONTENT" IS '자료본문';
   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."FILE_BOARD_VIEW" IS '자료조회수';
   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."FILE_NAME" IS '원본파일이름';
   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."FILE_RENAME" IS '재설정파일이름';
   COMMENT ON COLUMN "PROJECT"."FILE_BOARD"."FILE_PATH" IS '파일경로';
REM INSERTING into PROJECT.FILE_BOARD
SET DEFINE OFF;
Insert into PROJECT.FILE_BOARD (FILE_BOARD_NO,MEMBER_NUM,FILE_BOARD_DATE,FILE_BOARD_TITLE,FILE_BOARD_CONTENT,FILE_BOARD_VIEW,FILE_NAME,FILE_RENAME,FILE_PATH) values (70,1001,to_date('23/10/16','RR/MM/DD'),'test','<p>esteste</p>',3,'sample val','sample val','sample val');
Insert into PROJECT.FILE_BOARD (FILE_BOARD_NO,MEMBER_NUM,FILE_BOARD_DATE,FILE_BOARD_TITLE,FILE_BOARD_CONTENT,FILE_BOARD_VIEW,FILE_NAME,FILE_RENAME,FILE_PATH) values (71,1001,to_date('23/10/16','RR/MM/DD'),'IMGIMG','<p>test</p><p><img src="/app/summernoteImg/f5b3a6d6-689e-4f0c-91cb-bd21c8fac098.jpg" style="width: 550px;"><br></p>',7,'sample val','sample val','sample val');
Insert into PROJECT.FILE_BOARD (FILE_BOARD_NO,MEMBER_NUM,FILE_BOARD_DATE,FILE_BOARD_TITLE,FILE_BOARD_CONTENT,FILE_BOARD_VIEW,FILE_NAME,FILE_RENAME,FILE_PATH) values (74,1001,to_date('23/10/16','RR/MM/DD'),'test','<p><img src="/app/summernoteImg/7a417ff3-a1dd-4e72-af85-9c2fab053fcf.png" style="width: 25%;"></p><p><br></p><p>test</p>',4,'sample val','sample val','sample val');
--------------------------------------------------------
--  DDL for Index FILE_BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."FILE_BOARD_PK" ON "PROJECT"."FILE_BOARD" ("FILE_BOARD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FILE_BOARD
--------------------------------------------------------

  ALTER TABLE "PROJECT"."FILE_BOARD" MODIFY ("FILE_BOARD_NO" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."FILE_BOARD" MODIFY ("FILE_BOARD_DATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."FILE_BOARD" MODIFY ("FILE_BOARD_VIEW" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."FILE_BOARD" ADD CONSTRAINT "FILE_BOARD_PK" PRIMARY KEY ("FILE_BOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  
--------------------------------------------------------
-- Create Sequence for Table FILE_BOARD
--------------------------------------------------------
   create sequence file_board_no_seq start with 1 increment 
		by 1 maxvalue 500 minvalue 1 cycle;
